### PR TITLE
Updating installer download to newest version

### PR DESCRIPTION
**Pull request by scottwarren**
Would have liked to use the `latest` keyword, but there doesn't seem to be a wait to do that whilst linking directly to the file itself

### CODE REVIEW

**Comment by btoews** [comment]
Good call! I keep forgetting to update that. Should we maybe just link to the releases page instead (https://github.com/github/SoftU2F/releases)?

**Comment by scottwarren** [comment]
Happy to change the link if you like, to me it makes sense for maintainability, but I didn't want to change without talking about it 💃  😁  👍

**Comment by scottwarren** [comment]
Forgot to say: you can link to the `latest` release on that page: https://github.com/github/SoftU2F/releases/latest

**Comment by btoews** [comment]
Oh, cool. Let's do https://github.com/github/SoftU2F/releases/latest

**Comment by scottwarren** [comment]
I have updated the link, but in a seperate commit without rewriting history. Let me know if you want me to squash into one commit 👍

**Comment by btoews** [comment]
:boom: Thanks for opening this!

**Pull request merged**
