### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by CyberFlameGO**
Added a point to "Here are a few things you can do that will increase the likelihood of your pull request being accepted" and created a new section dedicated to submitting an issue. Also other minor edits. I'd also like the issue template to be updated to the new issue template workflow.

### CODE REVIEW

**Review by CyberFlameGO — COMMENTED** [review]
Just fixed some formatting from my previous commit

**Comment by CyberFlameGO** [comment]
Is there anything else I need to do or am doing wrong?

**Comment by ptoomey3** [comment]
I’ll take a look next week.

**Comment by CyberFlameGO** [comment]
Okay

**Review by ptoomey3 — APPROVED** [review]
LGTM

**Pull request merged**
