### PR TITLE
Add a deprecation message to the top of `README.md`.

### PR DESCRIPTION
**Pull request by lgarron**

### CODE REVIEW

**Comment by lgarron** [comment]
@ptoomey3, could you review this?

@btoews, let us know if you have any thoughts or suggestions before we implement this! Thanks for starting this back in the day. ❤️

**Comment by btoews** [comment]
Totally onboard with this 👍

**Comment by ptoomey3** [comment]
👍 - Should we move forward with [archiving the repo](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) to?

**Review by ptoomey3 — APPROVED** [review]
LGTM

**Pull request merged**
